### ISSUE TITLE
C4P Figma All Themes Library Optimization

### ISSUE THREAD

**Issue by RichKummer** [carbon-design-system/carbon-for-products-design-kit#1]
[Figma All themes C4IP library (view access)](https://www.figma.com/file/0F9dKH2abAd7gSfvnacfWf/(v11)-C4IP-BETA---All-Themes---Carbon-for-IBM-Products?type=design&node-id=1%3A1309&mode=design&t=6fBfToiU1oRf51Ug-1)

```[tasklist]
### Current components
- [ ] https://github.com/carbon-design-system/carbon-for-products-design-kit/issues/28
- [ ] https://github.com/carbon-design-system/carbon-for-products-design-kit/issues/7
- [ ] https://github.com/carbon-design-system/carbon-for-products-design-kit/issues/10
- [ ] https://github.com/carbon-design-system/carbon-for-products-design-kit/issues/12
- [ ] https://github.com/carbon-design-system/carbon-for-products-design-kit/issues/38
- [ ] https://github.com/carbon-design-system/carbon-for-products-design-kit/issues/4
- [ ] https://github.com/carbon-design-system/carbon-for-products-design-kit/issues/11
- [ ] https://github.com/carbon-design-system/carbon-for-products-design-kit/issues/2
- [ ] https://github.com/carbon-design-system/carbon-for-products-design-kit/issues/14
- [ ] https://github.com/carbon-design-system/carbon-for-products-design-kit/issues/13
- [ ] https://github.com/carbon-design-system/carbon-for-products-design-kit/issues/6
- [ ] https://github.com/carbon-design-system/carbon-for-products-design-kit/issues/30
- [ ] https://github.com/carbon-design-system/carbon-for-products-design-kit/issues/31
- [ ] https://github.com/carbon-design-system/carbon-for-products-design-kit/issues/23
- [ ] https://github.com/carbon-design-system/carbon-for-products-design-kit/issues/15
- [ ] https://github.com/carbon-design-system/carbon-for-products-design-kit/issues/20
```

```[tasklist]
### Current Patterns
- [ ] https://github.com/carbon-design-system/carbon-for-products-design-kit/issues/16
- [ ] https://github.com/carbon-design-system/carbon-for-products-design-kit/issues/17
- [ ] https://github.com/carbon-design-system/carbon-for-products-design-kit/issues/25
- [ ] https://github.com/carbon-design-system/carbon-for-products-design-kit/issues/19
- [ ] https://github.com/carbon-design-system/carbon-for-products-design-kit/issues/21
- [ ] https://github.com/carbon-design-system/carbon-for-products-design-kit/issues/24
- [ ] https://github.com/carbon-design-system/carbon-for-products-design-kit/issues/27
- [ ] https://github.com/carbon-design-system/carbon-for-products-design-kit/issues/18
- [ ] https://github.com/carbon-design-system/carbon-for-products-design-kit/issues/32
```

```[tasklist]
### Other
- [ ] https://github.com/carbon-design-system/carbon-for-products-design-kit/issues/41
- [ ] https://github.com/carbon-design-system/carbon-for-products-design-kit/issues/34
- [ ] https://github.com/carbon-design-system/carbon-for-products-design-kit/issues/39
```

```[tasklist]
### Follow-on tasks
- [ ] https://github.com/carbon-design-system/carbon-for-products-design-kit/issues/35
- [ ] https://github.com/carbon-design-system/carbon-for-products-design-kit/issues/36
```

```[tasklist]
### Deprecated
- [ ] https://github.com/carbon-design-system/carbon-for-products-design-kit/issues/29
- [ ] https://github.com/carbon-design-system/carbon-for-products-design-kit/issues/8
- [ ] https://github.com/carbon-design-system/carbon-for-products-design-kit/issues/9
- [ ] https://github.com/carbon-design-system/carbon-for-products-design-kit/issues/3
- [ ] https://github.com/carbon-design-system/carbon-for-products-design-kit/issues/22
```

```[tasklist]
### Net new components
- [ ] https://github.com/carbon-design-system/carbon-for-products-design-kit/issues/37
```

**Comment by oliviaflory** [comment]
## Notes from Oct 2

### Planning for stable release:

#### Patterns
- Create flows
- Export
- API key
- Saving
- Notifications panel
- Re-evaluate Add and select
   - Multiple requests to remove add/select from tearsheet
   - David suggested decoupling
   - Ties into definition of pattern and Pattern code?

#### Datagrid
- Discuss strategy for Data table / Data grid with Juan, Anna, Lauren
   - Datatable in core 20.9% of memory
   - Datagrid in Products 36.3% of memory
   - How this relates to Tanstack
- is there a possibility to move both Data table and Data grid extensions into a separate kit 
   - For file size
   - For Datagrid depending on Data table / complex auto layout issues
- Who would be responsible for maintaining:
   - Carbon team would need to be main owners and act as reviewers for approving 
   - Could we allow teams to branch and merge in order to avoid deletion/regression?
