### ISSUE TITLE
Figma migration: Novice to Pro/Onboarding

### ISSUE THREAD

**Issue by RichKummer** [carbon-design-system/carbon-for-products-design-kit#39]
Migrate v10 `Novice to pro` component to v11 (eventually will change name to `onboarding`).
```[tasklist]
### Tasks
- [x] Update components to v11
- [x] Update type tokens to v11
- [x] Update color tokens to v11
```
