### ISSUE TITLE
Figma v11 Slack announcement

### ISSUE THREAD

**Issue by RichKummer** [carbon-design-system/carbon-for-products-design-kit#59]
We need to announce that the Figma v11 library is leaving beta with a complete component and pattern set. 

**Tasks**
- [x] Create a Slack block for the announcement with relevant links.
- [ ] Identify channels to announce to.
- [ ] Push the announcement!

**Comment by RichKummer** [comment]
![Image](https://github.com/user-attachments/assets/5de53cec-4b87-41dd-9b7e-5003cb6e22f2)
